import { addDays, startOfWeek } from 'date-fns';
import { Worklog, WorklogState } from '../types/global.types';
import { formatDateToYYYYMMDD } from './date.service';

export const worklogsFakeData: Worklog[] = [
  {
    id: '52616',
    issue: { id: '', key: 'TSK-2', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 1)),
    timeSpentSeconds: 2700000,
    comment: 'Build fixen und Änderungen von Taher checken',
    state: WorklogState.Synced,
  },
  {
    id: '52619',
    issue: { id: '', key: 'TSK-2', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 1)),
    timeSpentSeconds: 3600000,
    comment: 'Taher Änderungen checken und Code Cleanup',
    state: WorklogState.Synced,
  },
  {
    id: '52621',
    issue: { id: '', key: 'TSK-2', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 1)),
    timeSpentSeconds: 2700000,
    comment: 'ET Livegang vorbereiten & Livegang',
    state: WorklogState.Synced,
  },
  {
    id: '52618',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 1)),
    timeSpentSeconds: 3600000,
    comment: 'WEBSITE23-282 | Breadcrumbs anpassen und paths bug fixen',
    state: WorklogState.Synced,
  },
  {
    id: '52622',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 1)),
    timeSpentSeconds: 7200000,
    comment: 'WEBSITE23-101 | Add audience select to footer',
    state: WorklogState.Synced,
  },
  {
    id: '52623',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 1)),
    timeSpentSeconds: 900000,
    comment: 'WEBSITE23-104 | TrustedShops badge behind menu',
    state: WorklogState.Synced,
  },
  {
    id: '52624',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 1)),
    timeSpentSeconds: 4500000,
    comment: 'WEBSITE23-77 | Sorting checken und „Relevantes zuerst“ einfügen',
    state: WorklogState.Synced,
  },
  {
    id: '52625',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 1)),
    timeSpentSeconds: 1800000,
    comment: 'WEBSITE23-286 | Panel Bug checken und wenn möglich fixen',
    state: WorklogState.Synced,
  },
  {
    id: '52614',
    issue: { id: '', key: 'TMH-2', summary: 'Projektleitung & Consulting' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 1)),
    timeSpentSeconds: 900000,
    comment: 'Byte Club',
    state: WorklogState.Synced,
  },
  {
    id: '52617',
    issue: { id: '', key: 'TMH-2', summary: 'Projektleitung & Consulting' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 1)),
    timeSpentSeconds: 900000,
    comment: 'Jira Issues checken',
    state: WorklogState.Synced,
  },
  {
    id: '52615',
    issue: { id: '', key: 'OCII-2', summary: 'General ticket for Internal times / Idle' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 1)),
    timeSpentSeconds: 900000,
    comment: 'Umzug Mails checken und Info an Timo',
    state: WorklogState.Synced,
  },
  {
    id: '52731',
    issue: { id: '', key: 'TSK-2', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 2)),
    timeSpentSeconds: 1800000,
    comment: 'Support Taher checkboxen & Formular allgemein',
    state: WorklogState.Synced,
  },
  {
    id: '52733',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 2)),
    timeSpentSeconds: 900000,
    comment: 'WEBSITE23-285 | Aufwandseinschätzung',
    state: WorklogState.Synced,
  },
  {
    id: '52734',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 2)),
    timeSpentSeconds: 4500000,
    comment: 'WEBSITE23-237 | New eyond filter option for cars',
    state: WorklogState.Synced,
  },
  {
    id: '52735',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 2)),
    timeSpentSeconds: 1800000,
    comment: 'Panel labels anpassen',
    state: WorklogState.Synced,
  },
  {
    id: '52736',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 2)),
    timeSpentSeconds: 1800000,
    comment: 'WEBSITE23-280 | Contact popup Absprache mit Becci',
    state: WorklogState.Synced,
  },
  {
    id: '52737',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 2)),
    timeSpentSeconds: 2700000,
    comment: 'WEBSITE23-101 | Add audiences to certificates',
    state: WorklogState.Synced,
  },
  {
    id: '52738',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 2)),
    timeSpentSeconds: 2700000,
    comment: 'Fix cms bug in production',
    state: WorklogState.Synced,
  },
  {
    id: '52739',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 2)),
    timeSpentSeconds: 3600000,
    comment: 'WEBSITE23-264 | Automatically redirect to correct homepage audience',
    state: WorklogState.Synced,
  },
  {
    id: '52740',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 2)),
    timeSpentSeconds: 3600000,
    comment: 'WEBSITE23-265 | Add interactive cards to HeroVideo & fix sal bugs',
    state: WorklogState.Synced,
  },
  {
    id: '52730',
    issue: { id: '', key: 'TMH-2', summary: 'Projektleitung & Consulting' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 2)),
    timeSpentSeconds: 900000,
    comment: 'Byte Club Daily',
    state: WorklogState.Synced,
  },
  {
    id: '52732',
    issue: { id: '', key: 'OCII-2', summary: 'General ticket for Internal times / Idle' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 2)),
    timeSpentSeconds: 1800000,
    comment: 'Absprache mit Nico von der IT zu Jumpcloud und anderen IT Themen',
    state: WorklogState.Synced,
  },
  {
    id: '52785',
    issue: { id: '', key: 'TSK-2', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 3)),
    timeSpentSeconds: 14400000,
    comment: 'Taher §14 Code Review und QA',
    state: WorklogState.Synced,
  },
  {
    id: '52786',
    issue: { id: '', key: 'TSK-2', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 3)),
    timeSpentSeconds: 900000,
    comment: 'Support Taher',
    state: WorklogState.Synced,
  },
  {
    id: '52783',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 3)),
    timeSpentSeconds: 3600000,
    comment: 'WEBSITE23-280 | Neue Contact / FAQ collection',
    state: WorklogState.Synced,
  },
  {
    id: '52784',
    issue: { id: '', key: 'TMH-2', summary: 'Projektleitung & Consulting' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 3)),
    timeSpentSeconds: 900000,
    comment: 'Byte Club Daily',
    state: WorklogState.Synced,
  },
  {
    id: '52787',
    issue: { id: '', key: 'TMH-2', summary: 'Projektleitung & Consulting' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 3)),
    timeSpentSeconds: 2700000,
    comment: 'Aufwände Januar',
    state: WorklogState.Synced,
  },
  {
    id: '52831',
    issue: { id: '', key: 'TSK-2', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 4)),
    timeSpentSeconds: 5400000,
    comment: 'Support / Peer Programming Taher ET',
    state: WorklogState.Synced,
  },
  {
    id: '52835',
    issue: { id: '', key: 'TSK-2', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 4)),
    timeSpentSeconds: 2700000,
    comment: 'Livegang planen/vorbereiten & prod merge',
    state: WorklogState.Synced,
  },
  {
    id: '52832',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 4)),
    timeSpentSeconds: 12600000,
    comment: 'WEBSITE23-280 | Neue Contact / FAQ collection',
    state: WorklogState.Synced,
  },
  {
    id: '52834',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 4)),
    timeSpentSeconds: 1800000,
    comment: 'Livegang planen/vorbereiten & prod merge',
    state: WorklogState.Synced,
  },
  {
    id: '52830',
    issue: { id: '', key: 'TMH-2', summary: 'Projektleitung & Consulting' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 4)),
    timeSpentSeconds: 900000,
    comment: 'Byte Club',
    state: WorklogState.Synced,
  },
  {
    id: '52829',
    issue: { id: '', key: 'OW-18', summary: 'Projektmanagement' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 4)),
    timeSpentSeconds: 2700000,
    comment: 'Orcaya Website CMS Absprache',
    state: WorklogState.Synced,
  },
  {
    id: '52833',
    issue: { id: '', key: 'OW-18', summary: 'Projektmanagement' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 4)),
    timeSpentSeconds: 1800000,
    comment: 'ORCAYA Website Checkin',
    state: WorklogState.Synced,
  },
  {
    id: '52836',
    issue: { id: '', key: 'AEB-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 4)),
    timeSpentSeconds: 900000,
    comment: 'Solid Sentry DB Fehler checken',
    state: WorklogState.Synced,
  },
  {
    id: '52967',
    issue: { id: '', key: 'TSK-2', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 1800000,
    comment: 'EW-65 | Neu Badge und Datum hinzufügen',
    state: WorklogState.Synced,
  },
  {
    id: '52968',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 900000,
    comment: 'WEBSITE23-123 | Remove line breaks in ListOfContents',
    state: WorklogState.Synced,
  },
  {
    id: '52972',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 900000,
    comment: 'WEBSITE23-264 | Adjust audiences order and labels',
    state: WorklogState.Synced,
  },
  {
    id: '52973',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 1800000,
    comment: 'WEBSITE23-267 | Support Taher TrustedShops Widget',
    state: WorklogState.Synced,
  },
  {
    id: '52974',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 9000000,
    comment: 'WEBSITE23-265 | Add text align option and fix SAL transition',
    state: WorklogState.Synced,
  },
  {
    id: '52975',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 900000,
    comment: 'WEBSITE23-290 & WEBSITE23-273 | Code review',
    state: WorklogState.Synced,
  },
  {
    id: '52977',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 900000,
    comment: 'WEBSITE23-273 | Code review',
    state: WorklogState.Synced,
  },
  {
    id: '52978',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 900000,
    comment: 'WEBSITE23-267 | Code review',
    state: WorklogState.Synced,
  },
  {
    id: '52979',
    issue: { id: '', key: 'TMH-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 900000,
    comment: 'WEBSITE23-269 | Code review',
    state: WorklogState.Synced,
  },
  {
    id: '52965',
    issue: { id: '', key: 'TMH-2', summary: 'Projektleitung & Consulting' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 900000,
    comment: 'Byte Club Daily',
    state: WorklogState.Synced,
  },
  {
    id: '52971',
    issue: { id: '', key: 'TMH-2', summary: 'Projektleitung & Consulting' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 900000,
    comment: 'Absprache mit Sebastian und Flo zur TMH Test E-Mail-Adresse',
    state: WorklogState.Synced,
  },
  {
    id: '52970',
    issue: { id: '', key: 'OW-48', summary: 'Meeting' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 2700000,
    comment: 'Absprache mit Sebastian und Flo zur Orcaya Webseite',
    state: WorklogState.Synced,
  },
  {
    id: '52966',
    issue: { id: '', key: 'OCII-2', summary: 'General ticket for Internal times / Idle' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 900000,
    comment: 'AWS Billing Checken',
    state: WorklogState.Synced,
  },
  {
    id: '52969',
    issue: { id: '', key: 'OCII-2', summary: 'General ticket for Internal times / Idle' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 1800000,
    comment: 'Nexus Checkout',
    state: WorklogState.Synced,
  },
  {
    id: '52976',
    issue: { id: '', key: 'AEB-5', summary: 'Development' },
    started: formatDateToYYYYMMDD(addDays(startOfWeek(new Date(), { weekStartsOn: 1 }), 5)),
    timeSpentSeconds: 1800000,
    comment: 'Solid DB export und Aufbereitung für Import von Guido',
    state: WorklogState.Synced,
  },
];
